const fetch = require("node-fetch");
const {MessageEmbed} = require('discord.js');
exports.handleCommand = function (args, msg, PREFIX) {
    return fetch("https://inspirobot.me/api?generate=true").then(r => r.text()).then(url => {
        let embed = new MessageEmbed();
        embed.setImage(url);
        embed.setColor(0xff69b4);
        embed.setFooter("Generated by inspirobot.me for " + msg.author.tag, msg.author.avatarURL({dynamic: true}));
        return msg.channel.send(embed);
    });
}